#!/usr/bin/env bash
# ec2-setup.sh — Bootstrap Nexa on a fresh Ubuntu 22.04 EC2 instance
#
# Bridges: WhatsApp (QR), LinkedIn (cURL), Instagram (cookie), X/Twitter (cookie)
# Frontend image pulled from ghcr.io/codzofrosh/nexa-frontend (must be public on GHCR)
#
# Usage: bash ec2-setup.sh [--skip-clone]
#
# Prerequisites:
#   - EC2 instance: t3.small+ (2 GB RAM minimum), Ubuntu 22.04
#   - Security group: ports 22 (SSH), 80 (HTTP) inbound; 8080 optional for API debug
#   - Repo cloned or --skip-clone passed

set -euo pipefail

REPO_URL="https://github.com/codzofrosh/nexa-beeper-connector.git"
APP_DIR="$HOME/nexa-beeper-connector"
SKIP_CLONE=false

for arg in "$@"; do
  [[ "$arg" == "--skip-clone" ]] && SKIP_CLONE=true
done

log() { echo -e "\033[1;34m[nexa]\033[0m $*"; }
err() { echo -e "\033[1;31m[error]\033[0m $*" >&2; exit 1; }

# ── 1. Install Docker + Docker Compose ───────────────────────────────────────
log "Installing Docker..."
if ! command -v docker &>/dev/null; then
  sudo apt-get update -qq
  sudo apt-get install -y ca-certificates curl gnupg lsb-release
  sudo install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  sudo chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
    | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  sudo apt-get update -qq
  sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  sudo usermod -aG docker "$USER"
  log "Docker installed — you may need to re-login for group changes to take effect."
else
  log "Docker already installed, skipping."
fi

# ── 2. Install Python 3.11 + pip (for setup.py) ──────────────────────────────
log "Installing Python..."
if ! command -v python3 &>/dev/null; then
  sudo apt-get install -y python3 python3-pip
fi
pip3 install -q requests pyyaml 2>/dev/null || true

# ── 3. Clone repo ─────────────────────────────────────────────────────────────
if [[ "$SKIP_CLONE" == "false" ]]; then
  if [[ -d "$APP_DIR" ]]; then
    log "Repo already exists at $APP_DIR, pulling latest..."
    git -C "$APP_DIR" pull --ff-only
  else
    log "Cloning repo..."
    git clone "$REPO_URL" "$APP_DIR"
  fi
else
  log "Skipping clone (--skip-clone passed)"
fi

cd "$APP_DIR"

# ── 4. Write .env ─────────────────────────────────────────────────────────────
EC2_IP=$(curl -sf http://169.254.169.254/latest/meta-data/public-ipv4 || echo "")

if [[ ! -f .env ]]; then
  log "Creating .env — fill in the blanks before running docker compose up."
  cat > .env <<EOF
# Auto-generated by ec2-setup.sh on $(date -u)
# Edit this file before running setup.py

# ── Matrix ────────────────────────────────────────────────────────────────
# Use your EC2 public IP (or a domain) as the server name
MATRIX_SERVER_NAME=${EC2_IP:-YOUR_EC2_IP}
MATRIX_USER=@admin:${EC2_IP:-YOUR_EC2_IP}
MATRIX_ACCESS_TOKEN=          # filled in automatically by setup.py

# ── Bridge bots ───────────────────────────────────────────────────────────
# These are auto-resolved from MATRIX_SERVER_NAME — only override if needed
# WHATSAPP_BRIDGE_BOT=@whatsappbot:${EC2_IP:-YOUR_EC2_IP}
# LINKEDIN_BRIDGE_BOT=@linkedinbot:${EC2_IP:-YOUR_EC2_IP}
# INSTAGRAM_BRIDGE_BOT=@instagrambot:${EC2_IP:-YOUR_EC2_IP}
# TWITTER_BRIDGE_BOT=@twitterbot:${EC2_IP:-YOUR_EC2_IP}

# ── CORS ──────────────────────────────────────────────────────────────────
EC2_PUBLIC_IP=${EC2_IP:-YOUR_EC2_IP}
ALLOWED_ORIGINS=http://${EC2_IP:-YOUR_EC2_IP}

# ── OAuth (optional) ──────────────────────────────────────────────────────
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
OAUTH_REDIRECT_BASE_URL=http://${EC2_IP:-YOUR_EC2_IP}/api/auth/oauth

# ── AI (optional — falls back to rule-based classifier if not set) ────────
OLLAMA_URL=
OLLAMA_MODEL=llama3.2:1b
EOF
  log ".env written to $APP_DIR/.env"
  log "⚠  Edit .env — set MATRIX_SERVER_NAME to your EC2 public IP."
  log "   MATRIX_ACCESS_TOKEN is filled in automatically by setup.py."
else
  log ".env already exists, skipping."
fi

# ── 5. Run bridge setup ───────────────────────────────────────────────────────
log ""
log "──────────────────────────────────────────────────────"
log " Next steps:"
log ""
log "  1. Edit $APP_DIR/.env"
log ""
log "  2. Generate bridge configs + Synapse admin user:"
log "       cd $APP_DIR && python3 bridge/auth/setup.py"
log ""
log "  3. Pull the frontend image and start the full stack:"
log "       cd $APP_DIR && docker compose pull && docker compose up -d --build"
log ""
log "  4. Open http://${EC2_IP:-YOUR_EC2_IP} in your browser."
log ""
log "  Bridges available after onboarding:"
log "    WhatsApp  → POST /api/onboard/whatsapp/start  (QR code)"
log "    LinkedIn  → DM @linkedinbot in Matrix, send: login"
log "    Instagram → DM @instagrambot in Matrix, send: login"
log "    X/Twitter → DM @twitterbot in Matrix,   send: login"
log "──────────────────────────────────────────────────────"
log ""
log "Done. Re-login (or run 'newgrp docker') if Docker was just installed."
